server:
  port: 8080
  servlet:
    context-path: /aaa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dtb1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
